using System.Globalization;
using System.Text;
using Catalyst.SpecGraph.Nodes;
using Catalyst.SpecGraph.Properties;

namespace Catalyst.LanguageCompilers.CSharp;

// Just raw dog it for now.
public class CSharpLanguageCompiler : LanguageCompiler
{
    public override CompiledFile CompileFile(File file)
    {
        StringBuilder sb = new();
        
        sb.AppendLine("//");
        sb.AppendLine($"// This file was generated by Catalyst's C# compiler at {DateTime.Now}.");
        sb.AppendLine("// It is recommended not to modify this file. Modify the source spec file instead.");
        sb.AppendLine("//");
        sb.AppendLine();

        Include[] includes = file.Includes.Distinct().ToArray();
        if (includes.Length > 0)
        {
            foreach (Include include in includes)
                sb.AppendLine($"using {include.Path};");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(file.Namespace))
            sb.AppendLine($"namespace {file.Namespace};").AppendLine();

        foreach (Class def in file.Classes)
        {
            sb.AppendLine($"public class {def.Name}").AppendLine("{");

            foreach (Property property in def.Properties)
            {
                if (property.Attributes.Count > 0)
                {
                    sb.Append("    ");
                    foreach (Attribute attribute in property.Attributes)
                    {
                        sb.Append($"[{attribute.Name}");
                        if (!string.IsNullOrWhiteSpace(attribute.Arguments))
                            sb.Append($"({attribute.Arguments})");
                        sb.AppendLine("]");
                    }
                }

                sb.Append("    public");
                if (!property.Type.EndsWith("?") && string.IsNullOrWhiteSpace(property.Value))
                    sb.Append(" required");

                sb.Append($" {property.Type} {property.Name} {{ get; set; }}");
                
                if (!string.IsNullOrWhiteSpace(property.Value))
                    sb.Append($" = {property.Value};");
                
                sb.AppendLine();
                sb.AppendLine();
            }

            foreach (Function function in def.Functions)
            {
                sb.AppendLine();
                
                sb.Append("    public");
                
                if (function.Static)
                    sb.Append(" static");

                sb.Append($" {function.ReturnType} {function.Name}(");

                for (int parameterIdx = 0; parameterIdx < function.Parameters.Count; parameterIdx++)
                {
                    sb.Append(function.Parameters[parameterIdx]);
                    if (parameterIdx < function.Parameters.Count - 1)
                        sb.Append(", ");
                }
                
                sb.AppendLine(")");
                
                sb.AppendLine("    {");

                sb.AppendLine($"        {function.Body}");
                
                sb.AppendLine("    }");
            }

            sb.AppendLine("}").AppendLine();
        }

        return new CompiledFile(file.Name, sb.ToString());
    }

    public override File CreateFile(FileNode fileNode)
    {
        string newFileName = fileNode.FileInfo.Name.Replace(fileNode.FileInfo.Extension, string.Empty).ToPascalCase() + ".cs";
        string newFilePath = Path.Combine(fileNode.FileInfo.DirectoryName ?? string.Empty, newFileName);
        
        File file = new(
            Name: newFilePath,
            Includes: [],
            Namespace: fileNode.Namespace.ToPascalCase(),
            Classes: []);

        return file;
    }

    protected override void AddPropertyType(File file, IPropertyType propertyType)
    {
        switch (propertyType)
        {
            case ListType:
            case MapType:
            case SetType:
                file.Includes.Add(new Include("System.Collections.Generic"));
                break;
        }
    }

    protected override void AddDefinition(File file, DefinitionNode definition)
    {
        List<Property> properties = [];
        foreach (KeyValuePair<string, PropertyNode> propertyNode in definition.Properties)
        {
            PropertyType propertyType = GetPropertyType(propertyNode.Value.BuiltType!);

            string? defaultValue = null;
            if (propertyNode.Value.Value is not null)
                defaultValue = GetDefaultValueForProperty(propertyNode.Value.Value);
            
            Property property = new Property(
                Name: propertyNode.Value.Name.ToPascalCase(),
                Type: propertyType.Name,
                Value: defaultValue,
                Attributes: [/* TODO */]);
            
            properties.Add(property);
        }

        Function serialiseFunc = new Function(
            Name: "ToBytes",
            ReturnType: "byte[]",
            Static: true,
            Parameters: [$"{definition.Name.ToPascalCase()} obj"],
            Body: "return System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(obj);");
        
        Function deserialiseFunc = new Function(
            Name: "FromBytes",
            ReturnType: $"{definition.Name.ToPascalCase()}?",
            Static: true,
            Parameters: ["byte[] bytes"],
            Body: $"return System.Text.Json.JsonSerializer.Deserialize<{definition.Name.ToPascalCase()}>(bytes);");
        
        Class def = new Class(
            Name: definition.Name.ToPascalCase(),
            Properties: properties,
            Functions: [serialiseFunc, deserialiseFunc]);
        
        file.Classes.Add(def);
    }

    protected override PropertyType GetPropertyType(IPropertyType propertyType)
    {
        PropertyType genPropertyType;
        switch (propertyType)
        {
            case AnyType:
                genPropertyType = new PropertyType("object");
                break;
            case BooleanType:
                genPropertyType = new PropertyType("bool");
                break;
            case DateType:
                genPropertyType = new PropertyType("DateTime");
                break;
            case FloatType:
                genPropertyType = new PropertyType("double");
                break;
            case IntegerType:
                genPropertyType = new PropertyType("int");
                break;
            case ListType listType:
                PropertyType innerListPropertyType = GetPropertyType(listType.InnerType);
                genPropertyType = new PropertyType($"List<{innerListPropertyType.Name}>");
                break;
            case MapType mapType:
                PropertyType innerKeyPropertyType = GetPropertyType(mapType.InnerTypeA);
                PropertyType innerValuePropertyType = GetPropertyType(mapType.InnerTypeB);
                genPropertyType = new PropertyType($"Dictionary<{innerKeyPropertyType.Name}, {innerValuePropertyType.Name}>");
                break;
            case SetType setType:
                PropertyType innerSetPropertyType = GetPropertyType(setType.InnerType);
                genPropertyType = new PropertyType($"HashSet<{innerSetPropertyType.Name}>");
                break;
            case StringType:
                genPropertyType = new PropertyType("string");
                break;
            case TimeType:
                genPropertyType = new PropertyType("TimeSpan");
                break;
            case ObjectType userType:
                genPropertyType = new PropertyType(userType.Name.ToPascalCase());
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(propertyType));
        }

        if (propertyType is IOptionalPropertyType)
            genPropertyType = new PropertyType($"{genPropertyType.Name}?");

        return genPropertyType;
    }
    
    protected override string GetDefaultValueForProperty(IPropertyValue propertyValue)
    {
        switch (propertyValue)
        {
            case BooleanValue booleanValue:
                return booleanValue.Value ? "true" : "false";
            case DateValue dateValue:
                return $"DateTime.Parse(\"{dateValue.Value:O}\")";
            case FloatValue floatValue:
                return floatValue.Value.ToString(CultureInfo.InvariantCulture);
            case IntegerValue integerValue:
                return integerValue.Value.ToString(CultureInfo.InvariantCulture);
            case ListValue listValue:
                StringBuilder sb = new();
                sb.Append('[');
                for (int itemIdx = 0; itemIdx < listValue.Values.Count; itemIdx++)
                {
                    IPropertyValue itemValue = listValue.Values[itemIdx];
                    sb.Append(GetDefaultValueForProperty(itemValue));
                    if (itemIdx < listValue.Values.Count - 1)
                        sb.Append(", ");
                }
                sb.Append(']');
                return sb.ToString();
            case MapValue mapValue:
                throw new NotImplementedException();
            case NullValue nullValue:
                return "null";
            case ObjectValue objectValue:
                throw new NotImplementedException();
            case StringValue stringValue:
                return $"\"{stringValue.Value}\"";
            case TimeValue timeValue:
                return $"TimeSpan.FromSeconds({timeValue.Value.TotalSeconds.ToString(CultureInfo.InvariantCulture)})";
            default:
                throw new ArgumentOutOfRangeException();
        }
    }
}